package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nano",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//firmware/lib/utils",
        "//firmware/platform",
    ],
)
